name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub
        uses: actions/checkout@master
      - name: Install and Build
        run: |
          yarn
          yarn build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /dist/index.js
